version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: scheme_auth_db
  pgadmin4:
    container_name: pgAdmin4
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@website.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"